### ISSUE TITLE
Implement redpill code

### ISSUE THREAD

**Issue by Valve** [fingerprintjs/fingerprintjs2#101]
To detect if FPJS is being run in an emulator.

Some ideas to start with: https://www.usenix.org/system/files/conference/woot14/woot14-ho.pdf

**Comment by gburtini** [comment]
I mocked up a little code to collect (some) of the data from that paper. I did not implement WebGL handlers (which is a significant source of information in that paper) as they do not provide a mechanism to isolate users who don't support WebGL from users who are in a virtual machine, preferring instead to show that all users who don't support WebGL are in a VM.

In general, the Ho et al. (2014) paper presents a cool idea, but does not present sufficient analysis of how random users on the Internet will look under these baseline vs. differential operations measures to implement something useful.

Hopefully @Valve has some idea how to go about this.

````js
var redPill = (function() {
  var TEXT_REPETITIONS = 1000,
    MEMORY_REPETITIONS = 1000,
    CONSOLE_REPETITIONS = 1000,
    LOCAL_STORAGE_REPETITIONS = 1000;

  function baselineOperation() {
    function textBaseline() {
        var addString = "Writes lots of text:";
        addString += Math.floor(Math.random() * 10000);
        var pNode = document.createElement("p");
        document.body.appendChild(pNode);
        for (var i = 0; i < TEXT_REPETITIONS; i++) {
            pNode.innerHTML = pNode.textContent + addString;
        }
    }

    function memoryBaseline() {
        var RANDOM = Math.floor(Math.random() * 1000000);
        var array = new Array();
        for(var i = 0; i < MEMORY_REPETITIONS; i++) {
            array.push(new Number(RANDOM));
        }
        for(var i = 0; i < array.length; i++) {
            array.pop();
        }
    }

    textBaseline();
    memoryBaseline();
  }
  function differentialOperation() {
    function consoleOperation() {
        var errorString = "Error: Writing to Console!";
        for(var i = 0; i < CONSOLE_REPETITIONS; i++) {
            console.log(errorString);
        }
    }

    function localStorageOperation() {
        var alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        var randomString = Array(500).join().split(',').map(function() { return alphabet.charAt(Math.floor(Math.random() * alphabet.length)); }).join('');

        for(var i = 0; i < LOCAL_STORAGE_REPETITIONS; i++) {
            window.localStorage.setItem(i, randomString);
        }

        for(var i = 0; i < LOCAL_STORAGE_REPETITIONS; i++) {
            window.localStorage.getItem(i, randomString);
        }
    }

    consoleOperation();
    // localStorageOperation();
  }

  // Woot14 (Ho, Boneh, Ballard and Provos)
  var time = new Date();
  var baseStart = time.getTime();
    baselineOperation();
  var baseTime = time.getTime() - baseStart;
  var diffStart = time.getTime ();
    differentialOperation();
  var diffTime = time.getTime() - diffStart;
  return {
    ratio: diffTime / baseTime, 
    differential: diffTime, 
    baseline: baseTime
  };
})();

**Comment by Valve** [comment]
thanks @gburtini! I will need to read the paper in full and then hopefully will be able to provide some feedback

**Comment by Valve** [comment]
I'm sorry for closing, but we'll be concentrating on stabilizing the library, not on adding new features in the foreseeable future. Closing as a non-feature.

**Comment by UltraFlux** [comment]
Just curious do either of you understand what the return values might represent?
ratio, differential, baseline?

**Comment by gburtini** [comment]
Hey @UltraFlux, it's been a few years... but I think ratio is what you care about, modulo maybe some thresholds for ensuring the difference and basetime are sane. Ratio is how much different the 'slow in VM' tasks are to the ones that are the same in VMs (i.e., "how VMy this is") -- you'd want to define a threshold on that.

**Comment by UltraFlux** [comment]
Hi @gburtini, thanks that makes perfect sense. Ideally selecting a threshold can be done by comparing what I know to be accurate and based on supporting variables that tie into FingerPrint2.

**Comment by gburtini** [comment]
It may not be that simple [1], but in the event you come up with something that does seem to work, I'd really love it if you let me know -- it is 100% a curiosity for me at this point (my application of this is no longer in development).

[1] These speeds are conditional on a lot of things that may not be revealed from the other variables directly -- other computational load, device specifics (RAM/CPU selection), etc. The big challenge I ran in to when I mocked up that implementation was speculating how we would get population level averages/difference thresholds (conditional on the relevant variables; at least user agent stuff) that triggered some controllable number of false positives.

**Comment by UltraFlux** [comment]
Will do, I am actually doing it out of curiosity myself. Currently storing about 500k records daily. Feel free to reach out directly if you want, perhaps we can figure something out.

Just to clarify I do store a few metrics related to CPU cores, Arch, Ram, and GPU which might work as features when reviewing the data from redpill. But overall I have about 100 ish reference points that span from fingerprint, parser, network, location, and geolocation. So hopefully I can come up with some type threshold where I have a high confidence on what is considered normal which should help identify the outliers.

**Comment by Valve** [comment]
Outside of library scope, closing as a non-feature.
