### ISSUE TITLE
Setup test runs on windows

### ISSUE THREAD

**Issue by Valve** [fingerprintjs/fingerprintjs2#105]
I have discovered a bug, present only on IE < 11. Tests didn't catch this bug, because they are run on PhantomJS + Linux. We need to setup the testing on a windows box too, ideally on all IE versions (6 - Edge).

**Comment by Valve** [comment]
Sauce labs has a plan for open-source projects, which we should use, I think.

**Comment by drBenway** [comment]
Maybe a setup with testswarm can help you?

**Comment by motnik** [comment]
As an alternative to sauce labs, Browser stack is also free for open source and can be used with this... 
On another note,  [karma Test Runner](https://karma-runner.github.io/), can be integrated (for unit tests) and it has launcher plugins for [Sauce-Labs](https://github.com/karma-runner/karma-sauce-launcher), and [Browserstack](https://github.com/karma-runner/karma-browserstack-launcher).

**Comment by Valve** [comment]
This has been implemented. Currently the tests are run on linux/mac/windows
