### ISSUE TITLE
Things to document

### ISSUE THREAD

**Issue by jonashaag** [fingerprintjs/fingerprintjs2#262]
- [x] iPhones of same model + OS version are indistinguishable https://github.com/Valve/fingerprintjs2/issues/209
- [x] Combine README information on options and wiki list of options
- [ ] List of options that are browser-dependent

**Comment by ningman** [comment]
I have the same problem，iPhones of same model + OS version are indistinguishable.Does anyone know how to solve this?

**Comment by jonashaag** [comment]
It's not possible.

**Comment by Valve** [comment]
Please use our pro version here. Start a trial: https://dashboard.fingerprintjs.com/signup @ningman

**Comment by Valve** [comment]
All the items from this list are implemented, closing.
