### ISSUE TITLE
IE 8: Invalid procedure call or argument

### ISSUE THREAD

**Issue by crossjs** [fingerprintjs/fingerprintjs2#322]
in IE 8

https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js#L422

```js
s.style.lineBreak = 'auto'
```

Cause to an Error: **Invalid procedure call or argument**

**Comment by Valve** [comment]
@jonashaag are we supporting IE8?

**Comment by Valve** [comment]
Just as a heads up, we'll be dropping IE support in V3

**Comment by Finesse** [comment]
IE9 and older aren't supported in v2

**Comment by Valve** [comment]
Here is a list of supported browsers: https://docs.fingerprintjs.com/pro/js-agent#supported-browsers

**Comment by Valve** [comment]
IE (all versions combined) was 0.98% from total traffic to https://fingerprintjs.com
At this stage the effort to continue maintaining it is disproportionate to the percentage of people using it (less than one percent).

Also Microsoft itself is dropping support for IE11 in its products in 2020, why we should support IE11 if MS decided not to support it?

**Comment by Finesse** [comment]
Because many users use it and business wants to track this users? I don't know the actual demand on tracking IE but I think this should be the factor to decide if we should support a browser.
