### ISSUE TITLE
getadblock can not remove ads

### ISSUE THREAD

**Issue by java0racle** [fingerprintjs/fingerprintjs2#334]
```js
try {
    // body may not exist, that's why we need try/catch
    document.body.appendChild(ads)
    result = document.getElementsByClassName('adsbox')[0].offsetHeight === 0
    document.body.removeChild(ads)
} catch (e) {
    result = false
}
```

`result = document.getElementsByClassName('adsbox')[0].offsetHeight === 0` throw error

`document.body.removeChild(ads)` can not remove element

on win7 IE8

**Comment by Finesse** [comment]
IE9 and older aren't supported in v2. Please open an issue if you face this problem in a modern browser.
