### ISSUE TITLE
Object Does Not Support This Action

### ISSUE THREAD

**Issue by killianbrackey** [fingerprintjs/fingerprintjs2#393]
### Problem description

- After the deployment of 1.8.4 and 1.8.5 there have been breaking changes popping up in IE11 Windows 7.  

- Bug appears to have been introduced in the following commit: https://github.com/Valve/fingerprintjs2/commit/54127aff6a35b39b147110d45bfd24255f4479d0

### Fingerprintjs2 version and devices used

[ ] I can reproduce the bug in https://github.com/Valve/fingerprintjs2/releases/tag/1.8.5 (most recent 1.x.x release)

[ ] I can reproduce the bug on these devices: IE11 Windows 7

### Minimal reproducing example

`npm i fingerprintjs2@1.8.5` in IE 11 on Windows 7 and generating a new Fingerprint.

**Comment by jonashaag** [comment]
Thanks for the report!

Can you share a traceback? I don't have access to a Windows machine

**Comment by jonashaag** [comment]
Please paste a unminified traceback or at least the name of the function that isn’t supported

**Comment by mwq27** [comment]
It's this line: https://github.com/Valve/fingerprintjs2/blob/1.8.5/fingerprint2.js#L118

```js
// In IE 11 when I run this:
var AudioContext = window.OfflineAudioContext || window.webkitOfflineAudioContext;
var context = new AudioContext();
// Throws -> Object doesn't support this action
```

**Comment by jonashaag** [comment]
Is `AudioContext != null` for you?

**Comment by mwq27** [comment]
Here's what I tried in the console of IE 11
```js
AudioContext != null
// false
```

**Comment by jonashaag** [comment]
Then I don’t understand how the code would even try to create an audio context since it’s explicitly checked for in the code. Please try with fingerprintjs master non-minified and post a full traceback

**Comment by outdooricon** [comment]
@jonashaag is there any chance of a fix soon? This is currently blocking us

**Comment by jonashaag** [comment]
It's not the minifying, it's an actual code bug in 1.8.5 (rather a missing fix). I released 1.8.6, please give it a try.

**Comment by outdooricon** [comment]
perfect, thank you 👍

**Comment by Finesse** [comment]
Looks like this is fixed
