### ISSUE TITLE
[DISCUSS] Calculating a proximity score, and automated testing

### ISSUE THREAD

**Issue by Magiweb** [fingerprintjs/fingerprintjs2#397]
This is in continuation of a discussion which started in https://github.com/Valve/fingerprintjs2/issues/366 between me, @jonashaag and @GrosSacASac.

So two things were brought up: 

1. The use of a hash makes fingerprinting a "yes or no" match where in reality tiny changes to the data (such as simply the browser version, or a new font) would cause the match to outright fail. The concept is to therefore return a "proximity score" (%) which would indicate the likelihood of it matching another already-discovered fingerprint. 

Obviously the first thing that comes to mind is that this would require a centralised databased of previously discovered fingerprints (browser data), which means we'll no longer be dealing with a pure client-side script as we need to compare data retrieved from the client with previously saved data in a central (server-side) database. 

The second issue would be how to calculate such a score. Presumably each criteria (browser agent, fonts, plugins, canvas etc) would have a certain weight to them - in other words, if a canvas hash is identical then perhaps that makes the likelihood of a match already significant, whereas if a browser version has changed then such data probably shouldn't affect the "proximity" very much at all.

2. Setting up a machine that can run automated tests on fingerprinting, and return results of match failures where matching was expected to be true. Has anyone considered setting up a selenium grid for this? It should be fairly simple to implement, but would require a server of some kind, perhaps on Amazon. 

I can help with this for sure, but I'm not particularly good at writing the actual tests, which are typically done in java. Thoughts?

**Comment by jonashaag** [comment]
Similarity: yes we would need a database. Maybe we can start an implementation as a separate project. Shouldn’t be too complex. 

Tests: problem with Selenium is that it doesn’t support anything except Firefox and Chrome afaik. These we can test manually really easily. What’s more interesting is IE, Edge, Safari and mobile browsers

**Comment by Magiweb** [comment]
@jonashaag - no idea why, but I didn't see your reply, nor was I notified (or it got lost in my mess of a mailbox) - apologies for the late reply and belated happy New Year.

For Similarity - I saw someone mention "Fuzzy Hashing" (I've referenced it here https://github.com/Valve/fingerprintjs2/issues/401). Perhaps this will be a simpler implementation?

Selenium supports Firefox, Chrome, IE, Safari and Opera so it's a pretty good spread. I'm not sure if they'll ever add support for "Edge" since I don't think you can install it as a standalone browser? Anyway, it's still a reasonable option I think.

**Comment by Valve** [comment]
I've just added support for testing with Karma and migrated all tests to Chrome headless.
Now it's trivial to add other browsers to the mix. Previously it was only PhantomJS (which is an old wreck already). Thanks for your suggestions

**Comment by Valve** [comment]
Any similarity calculations will only be in the Pro version, as it has a server-side component. 
OSS version is a pure JS library and cannot have algorithms, comparing the fingerprint with other fingerprints.
Closing this issue, please feel free to reopen with additional comments or feedback @Magiweb
