### ISSUE TITLE
Fuzzy hashing

### ISSUE THREAD

**Issue by dpblh** [fingerprintjs/fingerprintjs2#401]
### readme isn't contain any info about `Fuzzy hashing`

I thing you should give references on some examples or libs.
Or it should be implemented, because it's main difference between fingerprintjs and fingerprintjs2.

**Comment by jonashaag** [comment]
Not sure about this.

**Comment by Magiweb** [comment]
I second this. If fuzzy hashing is not being implemented in v2, then it's definitely something to bring back in. Browsers are actively making it harder to hash consistently; even simple page reloads could adjust (add / remove / sort differently) the fonts causing the hash to differ (this is just one example).

**Comment by Valve** [comment]
This component will be implemented in the pro version (device-level fingerprinting) that will ignore browser differences and provide device-level identifiers.
Closing this, please feel free to reopen with additional comments or feedback @dpblh
