### ISSUE TITLE
Different fingerprints in incognito and normal mode

### ISSUE THREAD

**Issue by Agronya** [fingerprintjs/fingerprintjs2#405]
Hello, i try to test your library https://valve.github.io/fingerprintjs2/ and detect that i have different fingerprints in normal and in incognito mode, because in incognito mode ad block plus not started (dont know why).  Hope it will help you

**Comment by Valve** [comment]
According to this: https://www.quora.com/What-is-the-percentage-of-Internet-users-that-employ-AdBlock-Plus-or-similar-ad-blocking-plugins
9.3% of users have ad-blocking of any kind (not only AdBlock).
AdBlock specifically can be as high as 4-5%. It's something that we could disable by default, I think, but not sure.

**Comment by Finesse** [comment]
Desktop Chrome disables extensions in Incognito mode by default (user needs to grant Incognito mod permission to each extension). But Safari (both on macOS and iOS) content blockers (at least Adguard) work both in plain and Private modes. This way we can fix the Incognito mode issue in Chrome while saving the entropy of Safari users.

@jonashaag @Valve Have you tries such approach?

**Comment by Valve** [comment]
we disabled adblock for entropy in the pro version. @Finesse 
We can do the same here.
We only care about Chrome and FF open-source ad-blockers.
For Safari adblockers are not as popular, but let's get some data first to decide.

**Comment by Finesse** [comment]
@Valve AdGuard (that I use on my iPhone) has about 9100 ratings. I think it can be a valuable source of entropy for similar iPhone users and we should at least collect statistics for this component.

I'll add AdBlock to the list of default excluded components for now.

**Comment by Finesse** [comment]
The `adBlock` component is excluded
