### ISSUE TITLE
Failed to get key 'enumerateDevices' in some browsers 

### ISSUE THREAD

**Issue by zizyzhang** [fingerprintjs/fingerprintjs2#407]
### Scenario

- What's the scenario, what happens and what did you expect to happen? 
   It just computes the fingerprints forever. But if I exclude the key 'enumerateDevices' it works. So I suggest to have a timeout for computing enumerateDevices

- What device and browser are you using?
  - "userAgent" : "Mozilla/5.0 (Linux; Android 8.1.0; vivo Y85 Build/OPM1.171019.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36 VivoBrowser/5.6.3.1"

  - "userAgent" : "Mozilla/5.0 (Linux; Android 6.0.1; Redmi 3S Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 MQQBrowser/6.2 TBS/044307 Mobile Safari/537.36 MicroMessenger/6.7.3.1360(0x26070333) NetType/WIFI Language/zh_CN Process/tools"

    these two browsers are all popular in china
- What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment.)
    2.0.0

### Fingerprint data

If applicable, provide the FULL DATA of all fingerprints involved using this jsfiddle https://jsfiddle.net/L2gLq4rg/85/.
Alternatively, provide a jsfiddle that reproduces the bug.

**Comment by zizyzhang** [comment]
No errors actually happened.

**Comment by Finesse** [comment]
This component is unstable so you may want to exclude it. We won't include it in v3, but if we do someday, we will consider your report.

**Comment by Finesse** [comment]
@zizyzhang BTW what are the browser names? How can I find them in Google Play or other store?
