### ISSUE TITLE
'Memory' and 'Timezone' data not captured for Mi Browser

### ISSUE THREAD

**Issue by rahulthapar15** [fingerprintjs/fingerprintjs2#418]
###### 1. What's the scenario, what happens and what did you expect to happen?
> Trying to capture user mobile device information, in this case 'memory' and timezone information.

###### What device and browser are you using?
> Device : Any Android Mobile Device
   Browser : Mi Browser
 NOTE : Chrome browser on these Mi Devices captures device memory.

###### What version of fingerprintjs are you using?
> Fingerprintjs2 v_2.0.3

> Checked on Mi Browser and Chrome browser on multiple devices (OnePlus, Xiaomi, Nokia)

**Comment by Valve** [comment]
Hi @rahulthapar15 
Thanks for the issue.
Unfortunately, we don't support "Mi browser". The list of supported browsers can be found here:
https://docs.fingerprintjs.com/pro/js-agent#supported-browsers

Please feel free to reopen with additional comments or feedback.
