### ISSUE TITLE
'Memory' data not captured for iOS Devices

### ISSUE THREAD

**Issue by rahulthapar15** [fingerprintjs/fingerprintjs2#419]
##### What's the scenario, what happens and what did you expect to happen? 
> Capturing device memory. Displays 'not available'

##### What device and browser are you using?
>Device : Any iOS mobile device
 Browser : Safari, Chrome

##### What version of fingerprintjs are you using?
> Fingerprintjs2 v_2.0.3

**Comment by Valve** [comment]
@rahulthapar15 can you please let me know what you expected to capture? I guess I don't fully understand this issue

**Comment by ishan3350** [comment]
Hi Valve,

Yes in IOS it is not showing memory.

deviceMemory = not available

**Comment by Valve** [comment]
@ishan3350 it's not supported on Safari: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/deviceMemory
Closing as this behavior is correct. 
Please feel free to reopen with additional comments or feedback.
