### ISSUE TITLE
Takes 3x more time(450ms) to capture fingerprints on IE11 on windows 10 

### ISSUE THREAD

**Issue by magizh** [fingerprintjs/fingerprintjs2#429]
### Scenario

- What's the scenario, what happens and what did you expect to happen? 
Go to https://fingerprintjs.com/ and click on "click here to generate fingerprint"  button at the bottom.

The time to compute fingerprint on this page is 3x when compared to 
Edge on wind 10, IE11 on win7 or any other browser. 

- What device and browser are you using?

Windows 10 IE 11

- What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment.)
whatever version is on  https://fingerprintjs.com/

### Fingerprint data

If applicable, provide the FULL DATA of all fingerprints involved using this jsfiddle https://jsfiddle.net/L2gLq4rg/85/.
Alternatively, provide a jsfiddle that reproduces the bug.

On IE11 win 10 

<img width="1180" alt="screen shot 2019-02-19 at 2 18 01 pm" src="https://user-images.githubusercontent.com/1396108/53053119-5f76da80-3455-11e9-90ea-7598843f20f0.png">

On IE 11 win 7 
<img width="731" alt="screen shot 2019-02-19 at 2 19 23 pm" src="https://user-images.githubusercontent.com/1396108/53053144-71587d80-3455-11e9-875a-901a0dc4bcfe.png">

On Edge Win 10 

<img width="596" alt="screen shot 2019-02-19 at 2 18 15 pm" src="https://user-images.githubusercontent.com/1396108/53053160-7caba900-3455-11e9-963d-607f34f2cce9.png">

**Comment by Valve** [comment]
thanks for this report. I think that a combination of IE11 + WIn10 is < 0.5% of global traffic so probably a low priority. What do you think @jonashaag

**Comment by jonashaag** [comment]
Absolutely

**Comment by Fusseldieb** [comment]
Sorry, but who still uses IE11? If you're running it on a legacy system, at least get Chrome for it.

**Comment by Valve** [comment]
Closing as IE11 will not be a priority for v3
