### ISSUE TITLE
Changing default options 

### ISSUE THREAD

**Issue by yairclassoos** [fingerprintjs/fingerprintjs2#439]
I've added customized options like this:
 ```
var options = {
           excludes: {
                       'canvas' : true
           },
};			
```
I've expected the merged options will grab both the default and my customized option, but only my customized options, have remained.   
I think that the merging of options doesn't go inside 2nd levels node.

**Comment by jonashaag** [comment]
I think the current semantics are more sane and we should explain them better in the documentation
