### ISSUE TITLE
WebGL 2 support

### ISSUE THREAD

**Issue by sanasol** [fingerprintjs/fingerprintjs2#440]
https://caniuse.com/#search=webgl%202
https://browserleaks.com/webgl

Many browsers already has support, so probably should be added in FP2.
Mostly desktop ofc, but more data is more data :)

What you think?

**Comment by jonashaag** [comment]
👍

**Comment by Valve** [comment]
well.. webgl is not a large source of entropy. I'm actually thinking about removing it entirely to make things faster, It won't make the lib less efficient, but will make it faster.

**Comment by jonashaag** [comment]
Don’t understand your reasoning here, why do you think it’s not a large source of entropy? Certainly more than some other components

**Comment by Valve** [comment]
I did some measurements, webgl wasn't significant enough to justify the amount of time it takes to generate. I'm not saying I'm determined to remove it, I'll test a lot more to do it, it's more of an FYI @jonashaag

**Comment by jonashaag** [comment]
Yeah considering the time it takes to generate maybe it makes sense. 

We should do a lot more documentation on quality of components, quirks of components etc.

**Comment by Valve** [comment]
Closing as WebGL 2 is not supported in Safari. Please feel free to reopen when Safari gets the support @sanasol

**Comment by Finesse** [comment]
@Valve Just FYI, WebGL 2 can be enabled as an experimental feature in Safari

**Comment by Valve** [comment]
thanks, @Finesse I think not worth adding that because by default it's disabled and very few users enable it.
