### ISSUE TITLE
Detected Fonts Change for Different Browser

### ISSUE THREAD

**Issue by nebi-frame** [fingerprintjs/fingerprintjs2#441]
### Detected Fonts Change for Different Browser

- I tried fingerprintjs for fonts on Google chrome 73.0.3683.75 and got 32 font type, I tried Firefox 65.0.2, got 33 font type, as you can see numbers do not match.
- Windows 10
- Latest version

**Comment by jonashaag** [comment]
Yeah unfortunately font fingerprints aren’t always accurate. Can you provide both fingerprint data?

**Comment by nebi-frame** [comment]
0
:
"Arial"
1
:
"Arial Black"
2
:
"Arial Narrow"
3
:
"Calibri"
4
:
"Cambria"
5
:
"Cambria Math"
6
:
"Comic Sans MS"
7
:
"Consolas"
8
:
"Courier"
9
:
"Courier New"
10
:
"Georgia"
11
:
"Helvetica"
12
:
"Impact"
13
:
"Lucida Console"
14
:
"Lucida Sans Unicode"
15
:
"Microsoft Sans Serif"
16
:
"MS Gothic"
17
:
"MS PGothic"
18
:
"MS Sans Serif"
19
:
"MS Serif"
20
:
"Palatino Linotype"
21
:
"Segoe Print"
22
:
"Segoe Script"
23
:
"Segoe UI"
24
:
"Segoe UI Light"
25
:
"Segoe UI Semibold"
26
:
"Segoe UI Symbol"
27
:
"Tahoma"
28
:
"Times"
29
:
"Times New Roman"
30
:
"Trebuchet MS"
31
:
"Verdana"
32
:
"Wingdings"
this is for chrome, firefox does not have Arial narrow only.

**Comment by nebi-frame** [comment]
any workaround for this that you suggest?

**Comment by jonashaag** [comment]
No, sorry, font fingerprinting is a very difficult topic and requires a ton of trial and error. None of the maintainers have time to do that at the moment. If you’re willing to invest some time I can guide you how to debug the issue yourself and share your results here.

**Comment by franck34** [comment]
@jonashaag can you please add a wiki page or something regarding the debugging method ?

ty

**Comment by jonashaag** [comment]
Don’t think it’s worth a wiki page. Are you going to debug it?

**Comment by franck34** [comment]
Not this case, but i'm sure i'll have to debug fonts stuff soon

**Comment by nebi-frame** [comment]
@jonashaag I'll definitely want to put some time to debug it, can you instruct me how to do ? so that I can contribute?

**Comment by Finesse** [comment]
The `fonts` component isn't browser independent. Similar issue: https://github.com/fingerprintjs/fingerprintjs2/issues/528.
