### ISSUE TITLE
Build before publish

### ISSUE THREAD

**Issue by GrosSacASac** [fingerprintjs/fingerprintjs2#466]
To make it easier to publish add a prepublish hook like so 

```
  "scripts": {
    "test": "karma start --single-run --browsers ChromeHeadless tests/karma.conf.js",
    "test:debug": "karma start --single-run=false --browsers Chrome tests/karma.conf.js",
    "gulp": "gulp",
    "lint": "standard --fix"
    "prepublishOnly": "npm run gulp",
},
```

Every time npm publish is used, gulp will run before.

I did the same in my projects and it works great:

https://github.com/GrosSacASac/worka/blob/master/package.json#L12

Note: Alternative to `prepublishOnly` is `prepare`, which will also run on github install (for the installer) and on npm install

**Comment by Valve** [comment]
@GrosSacASac thanks for the tip, will try it

**Comment by Finesse** [comment]
The build and publish process will be reworked in v3, therefore this issue will be inapplicable. We work mostly on v3 at the moment and consider only patches at v2 so we will keep the existing process in v2 as is.
