### ISSUE TITLE
Fingerprint2 is undefined inside an Electron app

### ISSUE THREAD

**Issue by F0RIS** [fingerprintjs/fingerprintjs2#469]
### Scenario

- Browser: Electron/4.1.0
- Version: 2.1.0

Initialization checks works incorrectly inside Electron. This is because you actually have "module" thing inside it and these checks do 
```module.exports = definition() ```
 instead of desired 
```context[name] = definition() ```

Here is my naive fix which is OK in my case, but not OK for the lib)
![image](https://user-images.githubusercontent.com/10178982/59022319-36d4ee00-8856-11e9-82e8-5f7c37a8c596.png)

To test it you can create simple Electron app with the code below and open any web site which uses Fingerprint2
```
var electron = require("electron");
var { app, BrowserWindow } = electron;

var mainWindow;

app.on("ready", function () {
    mainWindow = new BrowserWindow({
        width: 1280 + 400,
        height: 720 + 400,
        darkTheme: true,
    });

    mainWindow.webContents.session.clearCache(function () {
        mainWindow.loadURL("http://localhost:4200");
    });
});
``` 

I hope you can do a nice fix so this lib will work in Electron out of the box. Thanks.

**Comment by jonashaag** [comment]
I'm fine with that workaround, but maybe there's a proper way to solve this? How do other libraries make sure module initialisation is done correctly? (Without using any transpilers/preprocessors etc; at some point we should simply switch to modern JS)

**Comment by cekvenich** [comment]
In my code I wait for either 'deviceready' (electorn) or DOMContentLoaded (regular). Not sure if it will give you what you want.
But using modern .js is bad since ie11 has huge market share. Using typescript is cool, since it will do both es5 or es2016.

**Comment by Valve** [comment]
this potentially can be solved by this initiative: https://github.com/Valve/fingerprintjs2/issues/483
Once we get a normal module support, we should be able to solve Electron issues.

**Comment by cekvenich** [comment]
The problem w/ module support is that it can't be used of the CDN w/o packing.

**Comment by Valve** [comment]
@cekvenich yeah, once we have modules, we can generate a UMD module which will work on CDN. 
Essentially there will be two types of modules in the distribution: UMD (for CDN) and CommonJS (for Webpack, Browserify etc).

**Comment by AmirSasson** [comment]
I have kinda related scenario where the fingerprint is loaded dynamically from CDN on a browser on a site that includes a `requirejs`.
in this case it seems like i cant access the FIngerprint2 objects that usually available on the window scope.
seems like the first initialization condition is met:
```js
if (enableModule && typeof window !== 'undefined' && typeof define === 'function' && define.amd) {
    define(definition)
  }
```
and the define() function is called, 
and then you end up with **window.Fingerprint2 == undefined**
in addition i cant access the created object with require cause no ID is passed to the define() function. 
I have created a PR that work around it.
#525 
maybe someone on this thread can take a look and comment.
thanks

**Comment by Finesse** [comment]
FingeprintJS v2 is shipped in the UMD format. The problem you've described is a known problem between Electron and UMD. Please search solutions for UMD in general, for example, https://stackoverflow.com/q/32621988/1118709.

FingerprintJS v3 will be published in multiple formats including IIFE that doesn't clash with Electron.
