### ISSUE TITLE
IE11 timezone is undefined

### ISSUE THREAD

**Issue by krzepa** [fingerprintjs/fingerprintjs2#481]
### Scenario

Run ` Fingerprint2.get(function(data) {console.log(data)})` from browser console. It returns array containing object with key **timezone** however its value is **undefined**.

IE 11.1331.16299.0
Microsoft Windows [Version 10.0.16299.1365]

Fingerprintjs2 ver. 2.1.0 installed from npm.

**Comment by Valve** [comment]
@krzepa  a PR would be very much appreciated (with a test runner for Karma + IE11 plus a new test to confirm it's working fine on IE11).
