### ISSUE TITLE
Info needed :- touch_support and open_database options 

### ISSUE THREAD

**Issue by someshrathi02** [fingerprintjs/fingerprintjs2#512]
Hi ,
We are using the Fingerprintjs2 1.8 version 
We see Hash value is changing on same  ios device, between 2 different login. 

While investigating further it was found that below 2 option value changed  in 2 different login :- 

touch_support  option  - value changed from [0,true,true] to [5,true,true] 
open_database  option -  value changed from 1 to empty. 

Can you please clarify what those options means ? 
Also the above changes in value signifies what ?

**Comment by Valve** [comment]
Hi @someshrathi02. Are these different logins both using HTTPS?

**Comment by Finesse** [comment]
Closing it due to mission of response from the topic starter
