### ISSUE TITLE
Very poor website

### ISSUE THREAD

**Issue by x011** [fingerprintjs/fingerprintjs2#529]
For a company charging 100 usd per month for the pro version, your website is very poor, so poor that I cannot contact you directly and have to post a comment on GitHub to tell you that all the web-hooks are being posted empty.

**Comment by danpinto** [comment]
Hi,

For any future issues you can contact our support@fingerprintjs.com email and we will get back to you.

I see your account and someone from our tech team will reach out to you once they investigate the issue.

**Comment by Valve** [comment]
Hello @x011 ,

Tastes differ, and our website design may be poor to some people.

But I cannot agree that it's impossible to contact us. 

Every page has a footer, which states our support email and support phone number. 
See image below.

<img width="992" alt="Screen Shot 2020-06-28 at 3 58 52 PM" src="https://user-images.githubusercontent.com/27387/85958115-8c47d580-b958-11ea-8a49-b83808d85a74.png">
