### ISSUE TITLE
Rewriting into a modern workflow with basic TypeScript implementation

### ISSUE THREAD

**Issue by DZuz14** [fingerprintjs/fingerprintjs2#531]
I wanted to share a request that I think might help make adding new features and working on current one's a bit easier!

**_What about reworking and repurposing code into small modular files that worry about only completing a specific subset of the entire fingerprinting process_**? 

Basic TypeScript annotations would be super cool too!

I haven't thought any further than this, but I could imagine some of the files containing a class or function constructor that deals with it's own appropriate tasks. Examples like:

- Canvas.ts
- Navigator.ts
- FontChecker.ts
- LieDetector.ts
- ...etc 

Maybe a replacement to the done style callbacks could be implemented too.

**Comment by Valve** [comment]
Hi @DZuz14 thanks for this suggestion, we have plans to rewrite this in TS for v3.
I'll add more details to this ticket later in the process.

**Comment by DZuz14** [comment]
Awesome! Excited to see what you guys come up with.

**Comment by Finesse** [comment]
This issues almost duplicates https://github.com/fingerprintjs/fingerprintjs2/issues/394 therefore I'm closing this issue. Please subscribe to #394 for further information.
