### ISSUE TITLE
Publish new version to NPM

### ISSUE THREAD

**Issue by ertrzyiks** [fingerprintjs/fingerprintjs2#535]
We encountered an exception thrown by the library:
> a.value.join is not a function

it's apparently already fixed on the master branch, but there is no version with this fix published to npm.
https://github.com/fingerprintjs/fingerprintjs2/commit/d9d4b0dd266d57d53a06e05aa6356a1513fcf7da 

Can we have a new version published?

**Comment by Valve** [comment]
@ertrzyiks will publish today

**Comment by Valve** [comment]
@ertrzyiks just released version 2.1.2, please try it. If it works for you, please close the issue.
Thanks!

**Comment by ertrzyiks** [comment]
Amazing, thanks a lot @Valve . Will back to close this issue once we try it out!

**Comment by Valve** [comment]
@ertrzyiks please let me know if the fix worked and if we can close the issue, thanks!

**Comment by Valve** [comment]
ok, closing as resolved.

**Comment by ertrzyiks** [comment]
Sorry for the delay, it took a while to update it and observe the results as the issue was not frequent, looks like it works properly 👍
