### ISSUE TITLE
Ethical implications?

### ISSUE THREAD

**Issue by andrewmclagan** [fingerprintjs/fingerprintjs2#536]
How do the owners and maintainers of this project feel about the ethical implications of writing software that is (definitely) being used by corporations and governments for tracking individuals to unknown ends?

There are professional [code of ethics for software developers](https://www.computer.org/education/code-of-ethics) (IEEE).

Unfortunately – and unlike law, medicine or other fields of engineering – professional societies and their codes of ethics have virtually no influence within the information technology community and it's left to the individual to decide on their ethics.

This is not an attack. Just to provoke discussion and reflection.

**Comment by Valve** [comment]
Hi @andrewmclagan 

Thanks for raising this concern.

We have already had a long and hopefully productive discussion about ethical implications of device fingerprinting in general and this library in particular: https://github.com/fingerprintjs/fingerprintjs2/issues/430.

As one of the developers of this library, I personally feel about it how (I imagine) an iron ore miner would feel about the fact that this iron will (definitely) be used to manufacture guns. 

I'm closing this issue as a duplicate, please feel free to reopen with additional questions or comments.

Thanks

**Comment by andrewmclagan** [comment]
Thanks for the constructiveness! It is very easy to take these things personally, and in no way did I intend it so.

Close the issue of course, thank you.

The analogy you presented is a bit of a [straw man](https://en.wikipedia.org/wiki/Straw_man) argument. I believe a better analogy along the same vein would be:

| How I imagine a gun manufacturer would feel about the fact that their guns could be used to kill rather than protect innocent people.
