### ISSUE TITLE
Safari on iPhone producing same fingerprint for many users

### ISSUE THREAD

**Issue by camilodelvasto** [fingerprintjs/fingerprintjs2#539]
### Scenario

- What's the scenario, what happens and what did you expect to happen? 
We are collecting data from hundreds of thousands of users that interact with our platform, and we have found that there are many fingerprints that are duplicated —not unique. They all share the same browser version (13.1.1) and iOS version (13.5.1). There are reports from many different IP addresses, so we are convinced they are indeed different users sharing the same fingerprint (their geolocation coming from another service shows them hundreds of miles apart and there are only 20 minutes in between submissions). There aren't other browsers or OSs showing the same behavior in our sample (over 600k in the past 4 months).

- What device and browser are you using?
iOS 13.5.1
Safari 13.1.1

- What version of fingerprintjs are you using? (Bug reports not applicable to fingerprintjs master are subject to be closed without comment.)
2.1.0 (notice the 2.1.2 version was just released 5 days ago, so we haven't tested it on production yet)

### Fingerprint data

If applicable, provide the FULL DATA of all fingerprints involved using this jsfiddle https://jsfiddle.net/L2gLq4rg/85/.
Alternatively, provide a jsfiddle that reproduces the bug.

*Data with obscured IPs:

```
[{
  "browserReport": {
    "browser": {
      "name": "Safari",
      "version": "13.1.1"
    },
    "cookies": true,
    "flash": {
      "version": null
    },
    "ip": "XX.XX.183.174",
    "java": {
      "version": null
    },
    "os": {
      "name": "iOS",
      "version": "13.5.1"
    },
    "screen": {
      "colors": 32,
      "dppx": 3,
      "height": 667,
      "width": 375
    },
    "scripts": true,
    "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1",
    "viewport": {
      "height": 537,
      "layout": {
        "height": 537,
        "width": 375
      },
      "width": 375,
      "zoom": 1
    },
    "websockets": true,
    "lang": [
      "es-419"
    ],
    "timestamp": "Tue Jul 21 2020 11:39:07 GMT-0500 (-05)"
  },
  "fingerprint": "9aff284cacb360c082774b13c88b9d40"
},{
  "browserReport": {
    "browser": {
      "name": "Safari",
      "version": "13.1.1"
    },
    "cookies": true,
    "flash": {
      "version": null
    },
    "ip": "XX.XX.176.57",
    "java": {
      "version": null
    },
    "os": {
      "name": "iOS",
      "version": "13.5.1"
    },
    "screen": {
      "colors": 32,
      "dppx": 2,
      "height": 667,
      "width": 375
    },
    "scripts": true,
    "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1",
    "viewport": {
      "height": 537,
      "layout": {
        "height": 537,
        "width": 375
      },
      "width": 375,
      "zoom": 1
    },
    "websockets": true,
    "lang": [
      "es-419"
    ],
    "timestamp": "Tue Jul 21 2020 11:59:26 GMT-0500 (-05)"
  },
  "fingerprint": "9aff284cacb360c082774b13c88b9d40"
}]
```

**Comment by jonashaag** [comment]
Thanks for the report and thanks for using the issue template :-) This is a known issue, see multiple other reports in this repo. iOS devices of the same model  have identical fingerprints  because they _are_ identical.  We currently do not have a solution for this, except for taking into account non device factors as well (IP address etc). Maybe the pro version has a solution for this, idk.

**Comment by Valve** [comment]
@camilodelvasto thanks for reporting this. 
As @jonashaag mentioned, this is expected: identical iPhones will generate the identical fingerprints.

Please try our Pro version, which can handle this perfectly: https://dashboard.fingerprintjs.com/signup

**Comment by camilodelvasto** [comment]
Thanks for the que quickest response ever! I ended up combining the IP submissions with the fingerprint and I'm confident it's reducing dupes to around 98%.

**Comment by Valve** [comment]
Thanks
