### ISSUE TITLE
Why use OfflineAudioContext instead of AudioContext?

### ISSUE THREAD

**Issue by erikdemarco** [fingerprintjs/fingerprintjs2#541]
When checking for audio api support why do you use window.OfflineAudioContext instead of more universally accepted like window.AudioContext?

**Comment by Valve** [comment]
This code was contributed by @ProcrastinatorCp here: https://github.com/fingerprintjs/fingerprintjs2/commit/caf14daa9e2de105a8a55ae6d9c80667856f4afd

Please ask him directly about the specific choices that he made.

Closing for now, please feel free to reopen with more comments/questions.

**Comment by Finesse** [comment]
Because `AudioContext` can't return the result audio signal as an array of numbers.
