### ISSUE TITLE
Duplicate fingerprint id?

### ISSUE THREAD

**Issue by blackholevn** [fingerprintjs/fingerprintjs2#547]
### Scenario

- What's the scenario, what happens and what did you expect to happen? 
My customer of website report their account blocked. My website will blocked member account if detect fingerprint id use by other account. And when I check blocked account. I see fingerprint id is same. 
- What device and browser are you using?
Chrome Mobile Android
- What version of fingerprintjs are you using?
Version 2

Is there a case that can cause the id codes to match? Because this problem is encountered in many customers

**Comment by Valve** [comment]
Free version of FingerprintJS will have fingerprint collisions. 
If you need a higher accuracy, please consider our Pro version: https://dashboard.fingerprintjs.com/signup
You can start a free 10 day trial, which you can cancel any time.
Please let me know if you have any questions.
